name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:

jobs:

  build:
    runs-on: ubuntu-latest
    #run inside a container that has the prerequisites already installed
    container: 
      image: wcsim/wcsim:base
      env:
        TRAVIS_COMMIT: ${{ github.sha }}
        TRAVIS_PULL_REQUEST: ${{ github.event.number }}
        GitHubToken: ${{ secrets.GITHUB_TOKEN }}
      volumes:
        - /home/runner/work/WCSim/WCSim:/opt/HyperK/WCSim
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout-wcsim
        uses: actions/checkout@v2
        
      - name: checkout-valid
        run: |
          cd /root
          git clone https://github.com/WCSim/Validation.git

      - name: setup-wcsim
        run: |
          TRAVIS_COMMIT_MESG=`git log --pretty=format:%s -1`
          source /opt/HyperK/env-WCSim.sh
          
      - name: print env
        run: |
          env
          pwd
          ls -a

      - name: test_build
        run: /root/Validation/Tests.sh 1
