name: C/C++ CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
  release:

jobs:

  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /opt/HyperK/
    #run inside a container that has the prerequisites already installed
    container: 
      image: wcsim/wcsim:base
      env:
        TRAVIS_COMMIT: ${{ github.sha }}
        TRAVIS_PULL_REQUEST: ${{ github.event.number }}
        TRAVIS_COMMIT_MESG: ${{ github.event.head_commit.message }}
        GitHubToken: ${{ secrets.API_TOKEN_GITHUB }}
        ValidationPath: /root/Validation/
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout WCSim
        uses: actions/checkout@v2
        
      - name: Link WCSim directory
        run: ln -s ${GITHUB_WORKSPACE}/ /opt/HyperK/WCSim

      - name: Checkout WCSim/Validation
        run: |
          cd /root
          git clone https://github.com/WCSim/Validation.git
          
      #Temporarily get /usr/bin/time every job from yum
      # Need to add this to wcsim/wcsim:base ASAP
      - name: Get time
        run: yum install -y
          
      - name: Print environment
        run: |
          source /opt/HyperK/env-WCSim.sh
          cd WCSim
          env
          pwd
          ls -a

      - name: Test build
        run: |
          source /opt/HyperK/env-WCSim.sh
          cd WCSim
          /root/Validation/Tests.sh 1
          
      - name: Test physics
        run: |
          source /opt/HyperK/env-WCSim.sh
          cd WCSim
          /root/Validation/Tests.sh 2
